### ISSUE TITLE
Good first issue

### ISSUE THREAD

**Issue by Impa10r** [Impa10r/lnpos#1]
Refactor pay.html to display countdown (10 minutes max to pay) and 'Done' mark when paymen is received at Bitfinance.

**Comment by Coder-Manan** [comment]
There is no file named `pay.html` in the repo

**Comment by Impa10r** [comment]
Hello Coder-Manan, yes, I have solved this via res.write and res.end, instead of res.render. See post('/pay') section in the server.mjs . I append "PAYMENT RECEIVED" or "PAYMENT FAILED" phrase to the end of the payment page. I realized that moustache makes all my html files a template, so I cannot use <script> tags in them - they do not work.
